var fs = require('fs');
var path = require('path');
var webpack = require('webpack');
var HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {

    devtool: 'source-map',
    entry: [
        'whatwg-fetch',
        'webpack-dev-server/client?http://localhost:8065',
        'webpack/hot/only-dev-server',
        './src/index.js'
    ],
    output: {
        path: __dirname + '/__build__',
        filename: '[name].js',
        chunkFilename: '[name].chunk.js',
        publicPath: '/'
    },

    module: {
        loaders: [
            {
                test: /\.(ttf|eot|otf|svg|png|gif|woff|jpeg(2)?)(\?[a-z0-9]+)?$/,
                loader: 'file-loader'
            },
            {
                test: /\.css$/,
                exclude: [/global.css/,/flaticon.css/],
                loader: 'style!css-loader?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!postcss-loader'
            },
            {
                test:  [/global.css/,/flaticon.css/],
                loader: 'style!css-loader!postcss-loader'
            },
            {
                test: /\.js/,
                exclude: /node_modules/,
                loader: 'react-hot'
            },
            {
                test: /\.js/,
                exclude: /node_modules/,
                loader: 'babel-loader',
                query: {
                    presets: ['es2015', 'react', 'stage-0'],
                    plugins: ["transform-decorators-legacy"]
                }
            }
        ],
        include: path.join(__dirname, 'src')
    },

    plugins: [
        new webpack.optimize.CommonsChunkPlugin('common.js'),
        // new webpack.optimize.OccurenceOrderPlugin(),
        // new webpack.optimize.DedupePlugin(),
        // new webpack.optimize.UglifyJsPlugin({
        //     compressor: {warnings: false},
        // }),
        new webpack.DefinePlugin({
            'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV || 'development')
        }),
        new webpack.HotModuleReplacementPlugin(),
        new HtmlWebpackPlugin({
            template: 'index.html',
            inject: true // Inject all files that are generated by webpack, e.g. bundle.js
        })
    ]
};